name: "AWS ECS Container Definition Generator Action"
description: "Generates an AWS ECS Container Definition JSON file"
inputs:
  containerDefinitionRaw:
    description: "The container definition YAML/JSON as a string"
    required: false
  command:
    description: "The command to run in the container"
    required: false
  memory:
    description: "The hard limit (in MiB) of memory to present to the container"
    required: false
  cpu:
    description: "The number of cpu units reserved for the container"
    required: false
  memory_reservation:
    description: "The soft limit (in MiB) of memory to reserve for the container"
    required: false
  links:
    description: "The link parameter allows containers to communicate with each other without the need for port mappings"
    required: false
  dockerLabels:
    description: "The Docker labels to add to the container"
    required: false
  environment:
    description: "The environment variables to pass to a container in INI format"
    required: false
  image:
    description: "The image used to start a container"
    required: false
  linuxParameters:
    description: "Linux-specific modifications that are applied to the container, such as Linux kernel capabilities"
    required: false
    default: |
      initProcessEnabled: true
  logConfiguration:
    description: "The log configuration specification for the container"
    required: false
  mountPoints:
    description: "The mount points for data volumes in your container"
    required: false
  name:
    description: "The name of a container"
    required: false
  portMappings:
    description: "The list of port mappings for the container"
    required: false
  dependsOn:
    description: "The dependencies defined for container startup and shutdown"
    required: false
  healthCheck:
    description: "The health check command and associated configuration parameters for the container"
    required: false
  entryPoint:
    description: "The entry point that is passed to the container"
    required: false
outputs:
  container_definition:
    description: "The path to the file containing the container definition JSON"
  container_definition_raw:
    description: "The container definition JSON as a string"
runs:
  using: "node20"
  main: "dist/index.js"