name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: container
        with:
          name: Test

      - run: cat ${{ steps.container.outputs.container_definition }}

      - run: echo ${{ steps.container.outputs.container_definition_raw }}